version: "3"
services:
  springboot-app:
    container_name: spring_container
    build: ./CharityOrganization
    ports:
      - 8082:8081
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - spring-network
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: charity_organization
      MYSQL_ROOT_PASSWORD: root
    networks:
      - spring-network
volumes:
  mysql-data:
networks:
  spring-network: